### ISSUE TITLE
Pass lifespan to FastAPI application

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-web#26]
FastAPI recently supported [lifespan events](https://fastapi.tiangolo.com/advanced/events/#lifespan-events), which are passed to the application like this:
```py
from contextlib import asynccontextmanager

from fastapi import FastAPI


def fake_answer_to_everything_ml_model(x: float):
    return x * 42


ml_models = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Load the ML model
    ml_models["answer_to_everything"] = fake_answer_to_everything_ml_model
    yield
    # Clean up the ML models and release the resources
    ml_models.clear()


app = FastAPI(lifespan=lifespan)


@app.get("/predict")
async def predict(x: float):
    result = ml_models["answer_to_everything"](x)
    return {"result": result}
```
Does is mean that we cannot let the FastAPI component create the application object (since it's [not possible to pass a lifespan](https://github.com/asphalt-framework/asphalt-web/blob/8f4cdc81d3c9588ad19013e9668f351209f114c7/src/asphalt/web/fastapi.py#L76)), and that we must pass a ready-made application object?

**Comment by davidbrochart** [comment]
I guess lifespan events can be implemented at the `Component` level, when starting and at [teardown](https://asphalt.readthedocs.io/en/latest/userguide/contexts.html#handling-resource-cleanup).

**Comment by agronholm** [comment]
Took me a while to answer this, but yes, this is exactly why lifespans events are not supported here.
