### ISSUE TITLE
Test client

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-web#27]
It seems that a real server is used for [testing](https://github.com/asphalt-framework/asphalt-web/blob/206bc656e09c798618daf709ca91db1ce90ba8a7/tests/test_fastapi.py#L53-L58). I was wondering if there could be a test client, similar to what [Starlette](https://www.starlette.io/testclient) has, and for instance a `TestFastAPIComponent` that would not start a server?

**Comment by agronholm** [comment]
What would this accomplish?

**Comment by davidbrochart** [comment]
It would not require to launch a server, so I guess it's faster? And there would be no need to specify a base URL or port in the client.
Also, if we can use Starlette's test client, it's easier to test WebSocket sessions.

**Comment by agronholm** [comment]
Unless I'm mistaken, the test client would have to be specific to each type of framework, yes?

**Comment by agronholm** [comment]
What kind of difficulties are there with websocket that would be solved with a test client?

**Comment by davidbrochart** [comment]
> Unless I'm mistaken, the test client would have to be specific to each type of framework, yes?

I think so, yes.

> What kind of difficulties are there with websocket that would be solved with a test client?

Currently, for instance using an `httpx` client, one needs to find a WebSocket client that works well with it, such as [httpx-ws](https://github.com/frankie567/httpx-ws), because `httpx` [doesn't have WebSocket support](https://github.com/encode/httpx/issues/304). But `httpx`'s test client has.

**Comment by agronholm** [comment]
> But `httpx`'s test client has.

You mean Starlette's...?

**Comment by davidbrochart** [comment]
Yes, sorry.

**Comment by agronholm** [comment]
My point is that I don't want to shoulder the additional burden of maintaining several test clients if the benefits are only marginal.

**Comment by davidbrochart** [comment]
That's perfectly understandable, thanks for the feedback.
